export const FETCH_POKEMONS_START = 'FETCH_POKEMONS_START';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAIL = 'FETCH_POKEMONS_FAIL';

export const POKEMON_TO_SHOW = 'POKEMON_TO_SHOW';