export const FETCH_POKEMONS_START = 'FETCH_POKEMONS_START';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAIL = 'FETCH_POKEMONS_FAIL';

export const SET_POKEMON_TO_SHOW = 'SET_POKEMON_TO_SHOW';
export const SORT_POKEMONS = 'SORT_POKEMONS';
export const RESET_POKEMONS = 'RESET_POKEMONS';